# Generated by Django 3.2.3 on 2021-06-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_alter_factura_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='anio',
            field=models.IntegerField(default=2021),
        ),
    ]
